In [7]:
import pandas as pd
import numpy as np

In [8]:
path = 'Combinacao_Resultados.xlsx'
df = pd.read_excel(path, header=3, sheet_name='Fluxos')
df

,Malha,Posicao,Jacobi_Fluxo_Grupo1,Jacobi_Fluxo_Grupo2,Gauss_Fluxo_Grupo1,Gauss_Fluxo_Grupo2,Analitico_Fluxo_Grupo1,Analitico_Fluxo_Grupo2
0,1,0.2,0.025154,0.003734,0.025072,0.003722,0.003142,0.000466
1,2,0.4,0.075462,0.011201,0.075214,0.011165,0.009425,0.001399
2,3,0.6,0.125766,0.018669,0.125353,0.018608,0.015707,0.002332
3,4,0.8,0.176066,0.026135,0.175487,0.026050,0.021989,0.003264
4,5,1.0,0.226357,0.033600,0.225614,0.033490,0.028271,0.004197
...,...,...,...,...,...,...,...,...
495,496,99.2,0.226357,0.033600,0.225675,0.033499,0.028271,0.004197
496,497,99.4,0.176066,0.026135,0.175534,0.026056,0.021989,0.003264
497,498,99.6,0.125766,0.018669,0.125387,0.018613,0.015707,0.002332
498,499,99.8,0.075462,0.011201,0.075234,0.011168,0.009425,0.001399
499,500,100.0,0.025154,0.003734,0.025078,0.003723,0.003142,0.000466

In [9]:
cols_1 = ['Jacobi_Fluxo_Grupo1', 'Gauss_Fluxo_Grupo1']
cols_2 = ['Jacobi_Fluxo_Grupo2', 'Gauss_Fluxo_Grupo2']
max_1 = df[cols_1].max().to_numpy()
df[cols_1] = df[cols_1].div(max_1)
df[cols_2] = df[cols_2].div(max_1)
df['Posicao'] = df['Posicao'] - 50
df.to_csv('Combinacao_Resultados_Normalizado.csv', index=False)
df

,Malha,Posicao,Jacobi_Fluxo_Grupo1,Jacobi_Fluxo_Grupo2,Gauss_Fluxo_Grupo1,Gauss_Fluxo_Grupo2,Analitico_Fluxo_Grupo1,Analitico_Fluxo_Grupo2
0,1,-49.8,0.003174,0.000471,0.003157,0.000469,0.003142,0.000466
1,2,-49.6,0.009520,0.001413,0.009471,0.001406,0.009425,0.001399
2,3,-49.4,0.015867,0.002355,0.015784,0.002343,0.015707,0.002332
3,4,-49.2,0.022213,0.003297,0.022097,0.003280,0.021989,0.003264
4,5,-49.0,0.028558,0.004239,0.028409,0.004217,0.028271,0.004197
...,...,...,...,...,...,...,...,...
495,496,49.2,0.028558,0.004239,0.028417,0.004218,0.028271,0.004197
496,497,49.4,0.022213,0.003297,0.022103,0.003281,0.021989,0.003264
497,498,49.6,0.015867,0.002355,0.015788,0.002344,0.015707,0.002332
498,499,49.8,0.009520,0.001413,0.009473,0.001406,0.009425,0.001399
499,500,50.0,0.003174,0.000471,0.003158,0.000469,0.003142,0.000466